largest component size by common factor added
priyanshisharma/Leetcoding-Challenge pull request #17
Opened 2020-09-30 19:02 UTC by gayatri517

2020-09-30 20:07 UTC, priyanshisharma requested changes
* Can you please rename this file to `August_30_Largest_Component_Size_by_Common_Factor.cpp`.
* Please write a function for the following header, just like you would submit it on leetcode.
```
class Solution {
public:
    int largestComponentSize(vector<int>& A) {
        
    }
};
```

2020-10-01 01:37 UTC, gayatri517 commented
Hi @priyanshisharma i have made the changes kindly review them.

2020-10-01 22:16 UTC, priyanshisharma requested changes
Beats 80.88% after that tiny removal, please do the same, i'll be happy to merge this 🚀

2020-10-01 22:16 UTC, priyanshisharma commented on August/August_30_Largest_Component_Size_by_Common_Factor.cpp
> +        }3
```suggestion
        }
```

2020-10-02 04:39 UTC, gayatri517 commented
@priyanshisharma i have made that change kindly review it.

2020-10-02 09:27 UTC, priyanshisharma approved these changes
Looks perfect ✨ Merging this 🚀

2020-10-02 09:27 UTC, merged