Added solution for 26th August
priyanshisharma/Leetcoding-Challenge pull request #32
Opened 2020-09-30 21:09 UTC by AnjaliPatle

2020-09-30 22:15 UTC, priyanshisharma commented on August_26_fizz-buzz.cpp
> +public
```suggestion
public:
```

2020-09-30 22:15 UTC, priyanshisharma commented on August_26_fizz-buzz.cpp
> +    vectorstring fizzBuzz(int n) {
```suggestion
    vector<string> fizzBuzz(int n) {

```

2020-09-30 22:16 UTC, priyanshisharma commented on August_26_fizz-buzz.cpp
> +                s.push_back(FizzBuzz);
```suggestion
                s.push_back("FizzBuzz");

```

2020-09-30 22:16 UTC, priyanshisharma commented on August_26_fizz-buzz.cpp
> +                s.push_back(Fizz);
```suggestion
                s.push_back("Fizz");

```

2020-09-30 22:17 UTC, priyanshisharma commented on August_26_fizz-buzz.cpp
> +                s.push_back(Buzz);
```suggestion
                s.push_back("Buzz");

```

2020-09-30 22:20 UTC, priyanshisharma requested changes
Hey @AnjaliPatle I'm really glad to see your PR, but I've already assigned this to @sai-pothuri, please refer #1 I will definitely merge your PR if he doesn't come up with a solution in some time ✨ 

Untill then, there are some small changes required in your code to make it work, please check them out 😄

2020-10-01 00:05 UTC, AnjaliPatle commented
Hey @priyanshisharma no problem at all! I did not see the assignment before contributing 😅
Also, thanks for pointing out the errors, must have happend while changing file formats. I've committed the changes you suggested.

2020-10-01 16:39 UTC, priyanshisharma approved these changes
Thanks @AnjaliPatle , I see the other PR is made in Python and hence merging this as well 🙌

2020-10-01 16:39 UTC, merged