April Leet-code questions
priyanshisharma/Leetcoding-Challenge pull request #73
Opened 2020-10-05 03:03 UTC by Rahul171201

#54 Added April1 and April22 leet-code challenge solutions!

2020-10-05 18:47 UTC, priyanshisharma requested changes
Please write code for the function headers in Leetcode. i.e.
```
class Solution {
public:
    int subarraySum(vector<int>& nums, int k) {
        
    }
};
```
and
```
class Solution {
public:
    int singleNumber(vector<int>& nums) {
        
    }
};
```

2020-10-06 04:01 UTC, Rahul171201 commented
ok, working on it

2020-10-07 05:18 UTC, priyanshisharma requested changes
Please write your code according to the function definitions. Feel free to read the question on leetcode.

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April1.cpp
> +	for(int i=0;i<nums.length;i++)
```suggestion
	for(int i=0;i<nums.size();i++)

```

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April1.cpp
> +
No Return statement

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April1.cpp
> +        while(cin>>x){
Input is in `nums`. No console input is required.

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April22.cpp
> +	 for (int i = 0; i < nums.length; i++) {
```suggestion
	 for (int i = 0; i < nums.size(); i++) {   

```

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April22.cpp
> +            for (int j = i; j < n; j++) {
```suggestion
            for (int j = i; j < nums.size(); j++) {

```

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April22.cpp
> +                sum += A[j];
```suggestion
                sum += nums[j];

```

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April22.cpp
> +        cout<<count;
```suggestion
       return count;

```

2020-10-07 05:18 UTC, priyanshisharma commented on Leetcoding-April22.cpp
> +        while(cin>>x)
No console input is required

2020-10-08 04:47 UTC, Rahul171201 commented
I am really sorry @priyanshisharma , I should have had a good look at the question. just sending the final solutions.
Thankyou

2020-10-08 05:01 UTC, Rahul171201 commented
Final updated solutions. thankyou for help @priyanshisharma

2020-10-08 09:36 UTC, priyanshisharma requested changes
Its alright 🙌 
Your April1 solution fails for input `[-1]`, please debug the same.

2020-10-09 11:40 UTC, Rahul171201 commented
ok sure

2020-10-15 22:08 UTC, priyanshisharma approved these changes

2020-10-15 22:08 UTC, merged